name: translation_app_for_teacher
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  uuid: ^4.0.0
  http: ^1.0.0
  file_picker: ^8.0.0
  just_audio: ^0.9.40
  audio_session: ^0.1.19
  record: ^5.1.2
  flutter_audio_waveforms: ^1.2.1
  path: ^1.9.0
  csv: ^6.0.0
  url_launcher: ^6.0.0
  intl: ^0.19.0
  sqflite: ^2.3.0
  permission_handler: ^11.0.1
  flutter_tts: ^4.0.0
  speech_to_text: ^7.0.0
  archive: ^3.4.0
  mime: ^1.0.4
  share_plus: ^7.2.0
  image_picker: ^1.0.4
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
